apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel-container
        image: <your-docker-image>
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-registry-key
