name: CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Install dependencies
      run: composer install
    - name: Create SQLite database
      run: touch database/database.sqlite
    - name: Run migrations
      run: php artisan migrate
    - name: Run tests
      run: php artisan test

  failure:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Send failure notification email
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 587
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: GitHub Actions Build Failed
        body: The build has failed.
        to: monopich1823@gmail.com
        from: github-actions@example.com
